HAAR-588:  token endpoint
ministryofjustice/hmpps-auth pull request #1326
Opened 2022-07-01 15:32 UTC by ravmoj

RESET token endpoint in auth

2022-07-01 16:17 UTC, Mjwillis requested changes
Change the role name

2022-07-01 16:17 UTC, Mjwillis commented on src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/api/TokenController.kt
> +  @PreAuthorize("hasRole('ROLE_CREATE_USER')")
This should be ROLE_CREATE_EMAIL_TOKEN

2022-07-01 16:17 UTC, Mjwillis commented on src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/verify/TokenService.kt
> +    userToken.tokenExpiry = LocalDateTime.now().plusDays(7)
maybe make configurable as a param in request with default of 7d

2022-07-01 16:17 UTC, Mjwillis commented on src/test/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/api/TokenControllerIntTest.kt
> +      .headers(setAuthorisation("AUTH_ADM", listOf("ROLE_CREATE_USER")))
See role change

2022-07-01 17:00 UTC, ravmoj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/resource/api/TokenController.kt
> +  @PreAuthorize("hasRole('ROLE_CREATE_USER')")
Updated

2022-07-01 17:00 UTC, ravmoj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/oauth2server/verify/TokenService.kt
> +    userToken.tokenExpiry = LocalDateTime.now().plusDays(7)
Updated

2022-07-04 09:25 UTC, Mjwillis approved these changes
LGTM

2022-07-04 09:26 UTC, merged